onboarding = false

[theme]
name = "gruvbox"
auto_switch = false

[keys]
focus_pane_left = ["prefix+h", "ctrl+alt+h"]
focus_pane_right = ["prefix+l", "ctrl+alt+l"]
focus_pane_top = ["prefix+k", "ctrl+alt+k"]
focus_pane_down = ["prefix+j", "ctrl+alt+j"]
navigate_workspace_up = ["alt+1", "up"]
navigate_workspace_down = ["alt+2", "down"]
