#!/bin/bash
# the pbcopy script
if [[ $(hostname) =~ "guilhermeleobas-server" ]]; then
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
else
  tee <&0 | clip.exe
  exit 0
fi

